name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ruby-3.3, ruby-3.4.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Erb Lint
        run: bundle exec erb_lint --lint-all

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ruby-3.3, ruby-3.4.2]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: raif_dummy_test
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/raif_dummy_test
      # REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Set up database
        run: bin/rails app:db:prepare

      - name: Run tests
        run: bundle exec rspec

  test-mysql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ruby-3.3, ruby-3.4.2]
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      RAILS_ENV: test
      DATABASE_URL: mysql2://127.0.0.1:3306

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential default-libmysqlclient-dev git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Update database.yml for MySQL
        run: |
          cat > spec/dummy/config/database.yml << EOL
          default: &default
            adapter: mysql2
            encoding: utf8mb4
            pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
            username: root
            password:
            socket: /tmp/mysql.sock

          development:
            <<: *default
            database: raif_dummy_development

          test:
            <<: *default
            database: raif_dummy_test
          EOL

      - name: Create database
        run: bin/rails app:db:create 

      - name: Run Migrations 
        run: bin/rails app:db:migrate:reset

      - name: Run tests
        run: bundle exec rspec
